// <auto-generated />
using System;
using LearningAssistant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningAssistant.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260710122359_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("LearningAssistant.Models.LearningItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LearningMaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LearningSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LearningMaterialId");

                    b.HasIndex("LearningSessionId");

                    b.ToTable("LearningItems");
                });

            modelBuilder.Entity("LearningAssistant.Models.LearningMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LearningMaterials");
                });

            modelBuilder.Entity("LearningAssistant.Models.LearningSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LearningSessions");
                });

            modelBuilder.Entity("LearningAssistant.Models.LearningItem", b =>
                {
                    b.HasOne("LearningAssistant.Models.LearningMaterial", "LearningMaterial")
                        .WithMany("Items")
                        .HasForeignKey("LearningMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningAssistant.Models.LearningSession", "LearningSession")
                        .WithMany("Items")
                        .HasForeignKey("LearningSessionId");

                    b.Navigation("LearningMaterial");

                    b.Navigation("LearningSession");
                });

            modelBuilder.Entity("LearningAssistant.Models.LearningMaterial", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("LearningAssistant.Models.LearningSession", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
